version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building app..."
      - npm run build || echo "No build step required"
      - zip -r app.zip * .[^.]* # zips everything including hidden files
artifacts:
  files:
    - app.zip
  base-directory: .
#
